# Generated by Django 2.1.7 on 2019-03-20 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DecimalField(decimal_places=10, max_digits=32, verbose_name='当前时间')),
                ('money', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='输入金额')),
                ('remarks', models.CharField(max_length=200, verbose_name='备注信息')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='用户名')),
                ('phone_num', models.CharField(max_length=32, unique=True, verbose_name='手机号')),
                ('pwd', models.CharField(max_length=32, verbose_name='用户密码')),
            ],
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.IntegerField(choices=[(0, 'female'), (1, 'male')], verbose_name='性别')),
                ('age', models.CharField(max_length=10)),
                ('job', models.CharField(max_length=32)),
                ('salary', models.IntegerField(choices=[(0, '<2000'), (1, '2000-5000'), (2, '5000-8000'), (3, '8000-10000'), (4, '10000<')], verbose_name='薪水级别')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bill_count_app.User')),
            ],
        ),
        migrations.AddField(
            model_name='billdetail',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bill_count_app.User'),
        ),
    ]
