# Generated by Django 2.1.7 on 2019-03-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_count_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billdetail',
            name='money',
            field=models.FloatField(verbose_name='money'),
        ),
        migrations.AlterField(
            model_name='billdetail',
            name='remarks',
            field=models.CharField(max_length=200, verbose_name='remarks'),
        ),
        migrations.AlterField(
            model_name='billdetail',
            name='time',
            field=models.FloatField(verbose_name='time_for_now'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_num',
            field=models.CharField(max_length=32, unique=True, verbose_name='telephone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pwd',
            field=models.CharField(max_length=32, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=32, unique=True, verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='gender',
            field=models.IntegerField(choices=[(0, 'female'), (1, 'male')], verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='salary',
            field=models.IntegerField(choices=[(0, '<2000'), (1, '2000-5000'), (2, '5000-8000'), (3, '8000-10000'), (4, '10000<')], verbose_name='level_salary'),
        ),
    ]
